### ISSUE TITLE
Crashes with py3270.CommandError: Keyboard Locked

### ISSUE THREAD

**Issue by breaktoprotect** [singe/mainframe_brute#1]
mainframe_brute seems to crash whenever it gets a 'hit' (e.g. MACRO: TSO MACRO Found!).

Target is a z/OS 1.10 (emulated)
Attack platform: Kali (debian)

Any ideas what might have caused this?

Console dump:
```
root@Sukhoi:~/Desktop/Mainframe_Arsenals/mainframe_brute# ./mainframe_bruter.py -x 192.168.157.150:3270 -v -a applids_quick.txt
[+] z/OS Mainframe Bruteforcer
[+] Target Acquired		: 192.168.157.150:3270
[+] APPLID Bruting		: Enabled
[+] APPLID File			: applids_quick.txt
[+] Slowdown is			: 0
[+] Attack platform		: Linux
[+] ULTRA Hacker Movie Mode	: Disabled
[+] Connecting to 192.168.157.150:3270
[+] Checking if in VTAM
[!] The host is slow, increasing delay by 0.1s to: 0.1
	[+] Starting APPLID Enumeration
	[!] APPLID: TSO Invalid (bad response)
	[*] MACRO: TSO MACRO Found!
Traceback (most recent call last):
  File "./mainframe_bruter.py", line 433, in <module>
    brute_APPLID(em,results,appfile)
  File "./mainframe_bruter.py", line 243, in brute_APPLID
    em.delete_field() #Some inputs are dumb, and we need to blank the previous command
  File "/usr/lib/python2.7/dist-packages/py3270-0.3.5-py2.7.egg/py3270/__init__.py", line 460, in delete_field
    self.exec_command(b'DeleteField')
  File "/usr/lib/python2.7/dist-packages/py3270-0.3.5-py2.7.egg/py3270/__init__.py", line 299, in exec_command
    c.execute()
  File "/usr/lib/python2.7/dist-packages/py3270-0.3.5-py2.7.egg/py3270/__init__.py", line 77, in execute
    return self.handle_result(result.decode('ascii'))
  File "/usr/lib/python2.7/dist-packages/py3270-0.3.5-py2.7.egg/py3270/__init__.py", line 95, in handle_result
    raise CommandError(msg.decode('ascii'))
py3270.CommandError: Keyboard locked
```

**Comment by Imraneouelfaquir98** [comment]
I have the same problem
